hmLoadTopic({
hmKeywords:"",
hmTitle:"Application Icon",
hmPrevLink:"window-icon.html",
hmNextLink:"third-party-wpf-control-librar.html",
hmParentLink:"fsharp-wpf-code-behind-application.html",
hmBreadCrumbs:"<a href=\"fsharp-wpf-code-behind-application.html\">F# WPF Code Behind Application<\/a>",
hmTitlePath:"F# WPF Code Behind Application > Application Icon",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Application Icon<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Create a text file named AppIcon.rc, with the following content.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div style=\"text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 0px;\"><table style=\"background-color:#f8f8f8; border:solid thin #c0c0c0; border-spacing:0px;\">\n\r<tr style=\"text-align:left;vertical-align:top;\">\n\r<td style=\"vertical-align:top; padding:0.4375rem; border:none\"><p class=\"p_CodeExample\"><span class=\"f_CodeExample\">1&nbsp;ICON&nbsp;&quot;AppIcon.ico&quot;<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">You will need an icon file named AppIcon.ico for this to work, but of course you can adjust the names to your liking.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Run the following command.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div style=\"text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 0px;\"><table style=\"background-color:#f8f8f8; border:solid thin #c0c0c0; border-spacing:0px;\">\n\r<tr style=\"text-align:left;vertical-align:top;\">\n\r<td style=\"vertical-align:top; padding:0.4375rem; border:none\"><p class=\"p_CodeExample\"><span class=\"f_CodeExample\">&quot;C:\\Program&nbsp;Files&nbsp;(x86)\\Windows&nbsp;Kits\\10\\bin\\x64\\rc.exe&quot;&nbsp;\/v&nbsp;AppIcon.rc<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">If you can\'t find rc.exe in this location, then search for it in <span style=\"font-weight: bold;\">C:\\Program Files (x86)\\Windows Kits<\/span>. If you still can\'t find it, then download Windows SDK from Microsoft.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">A file named AppIcon.res will be generated.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">In Visual Studio, open the project properties. Select the <span style=\"font-weight: bold;\">Application<\/span> page.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">In the text box titled <span style=\"font-weight: bold;\">Resource File<\/span>, type <span style=\"font-style: italic;\">AppIcon.res<\/span> (or <span style=\"font-style: italic;\">Images\\AppIcon.res<\/span> if you put it there), and then close the project properties to save.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">An error message will appear, stating <span style=\"text-decoration: underline;\">The resource file entered does not exist.<\/span> Ignore this. The error message will not reappear.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Rebuild. The executable will then have an application icon, and this shows in File Explorer. When running, this icon will also appear in Task Manager.<\/p>\n\r"
})
